language: java

jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE spring;'
  - mysql -e "create user 'springuser'@'localhost' identified by 'password'"
  - mysql -e "grant all on spring.* to 'springuser'@'localhost' identified by 'password'"

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2

notifications:
  email: false